#!/bin/bash
echo "input filename"
read filename
echo "input prototype without semicolon tho"
read prototype
echo "#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include \"main.h\"
/**
 * $prototype - Entry point
 *
 * Return: Always 0 (Success)
 */
$prototype
{

}" > $filename
chmod u+x $filename
sed -i '$ d' main.h >> main.h
echo "$prototype;
#endif" >> main.h
vi $filename

